import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Components/Client/Header";

export const metadata: Metadata = {
  title: "Khizer hussain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <Header />
          <main>{children}</main>
        </main>
      </body>
    </html>
  );
}
